### PR TITLE
fix: pass pkg-config include dirs to bindgen

### PR DESCRIPTION
**Pull request by tie**
See also https://github.com/rust-lang/rust-bindgen/issues/1247

### CODE REVIEW

**Comment by zhangyuannie** [comment]
Thanks!

**Comment by zhangyuannie** [comment]
I'll revert this as I believe pkg_config probe already outputted the necessary cargo stuffs so there's no need to add include args again.

Let me know if you have an actual issue that is fixed by this, if so we can add it back.

**Comment by tie** [comment]
@zhangyuannie, it does not, arguments for C compiler include directories are *not* automatically added for bindgen invocation. Can you please rollback this revert?

This is probably working for you because libtrfsutil headers were installed in shared system location, e.g. `/usr/include`, that is added to the search path by default.

<details>
<summary><code>$ cargo build</code></summary>

```
   Compiling libbtrfsutil-sys v0.2.0
error: failed to run custom build command for `libbtrfsutil-sys v0.2.0`

Caused by:
  process didn't exit successfully: `/home/tie/infra/btrfs-rollback/target/debug/build/libbtrfsutil-sys-462ef71e526bcc82/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBBTRFSUTIL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBBTRFSUTIL_STATIC
  cargo:rerun-if-env-changed=LIBBTRFSUTIL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=SYSROOT
  cargo:rerun-if-env-changed=LIBBTRFSUTIL_STATIC
  cargo:rerun-if-env-changed=LIBBTRFSUTIL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rustc-link-search=native=/nix/store/gs94jq13mn8582sypl0702lf0zv1i24d-btrfs-progs-6.7/lib
  cargo:rustc-link-lib=btrfsutil
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBBTRFSUTIL_STATIC
  cargo:rerun-if-env-changed=LIBBTRFSUTIL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:1:10: fatal error: 'btrfsutil.h' file not found
  thread 'main' panicked at /home/tie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libbtrfsutil-sys-0.2.0/build.rs:22:10:
  Unable to generate bindings: ClangDiagnostic("wrapper.h:1:10: fatal error: 'btrfsutil.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
</details>

I can work around this issue by defining `BINDGEN_EXTRA_CLANG_ARGS=-I${btrfs-progs}/include` environment variable, but I’d rather have it working by default since build script already gets required flags from pkg_config probe.

**Comment by zhangyuannie** [comment]
Sounds good, released a new version with this patch.

**Pull request merged**
